src/app/chat-message/chat-message.component.html, src/app/chat-window/chat-window.component.html, src/app/chat-window/chat-window.component.less
Signed-off-by: invinciblejai <mailjai.vardhan@gmail.com>
=> styles for chat

package.json, src/app/chat-window/chat-window.component.ts, src/app/dependency-editor/dependency-editor.component.html, src/app/dependency-editor/dependency-editor.component.ts
Signed-off-by: invinciblejai <mailjai.vardhan@gmail.com>
=> adds event emitter for chat

src/app/chat-message/chat-message.component.html, src/app/data/chat-example-data.ts
Signed-off-by: invinciblejai <mailjai.vardhan@gmail.com>
=> updates chat text

src/app/application/application.component.html, src/app/packages/packages.component.html
Signed-off-by: invinciblejai <mailjai.vardhan@gmail.com>
=> fixes style issues, CVE

src/app/add-dependency/add-dependency.component.html, src/app/add-dependency/add-dependency.component.less, src/app/alert-box/alert-box.component.html, src/app/alert-box/alert-box.component.less, src/app/alert-box/alert-box.component.ts, src/app/current-project/current-project.component.html, src/app/current-project/current-project.component.less, src/app/current-project/current-project.component.ts, src/app/dependency-editor/dependency-editor.component.html, src/app/dependency-editor/dependency-editor.component.ts, src/app/insights/insights.component.html, src/app/insights/insights.component.ts, src/app/license/license.component.html, src/app/license/license.component.ts, src/app/security/security.component.html, src/app/security/security.component.ts
When runtime and mission are not selected how the screen look like
=> default screen changes included

src/app/dependency-editor/dependency-editor.component.html, src/app/dependency-editor/dependency-editor.component.less, src/app/dependency-editor/dependency-editor.component.ts
When runtime and mission are not selected how the screen look like
=> Removal of heading from dependency editor and no data scenario handled

README.adoc
=> fix(release): trigger a release to test

src/app/add-dependency/add-dependency.component.html, src/app/add-dependency/add-dependency.component.less, src/app/add-dependency/add-dependency.component.ts, src/app/insights/insights.component.html, src/app/insights/insights.component.less
1. fix(style): changes the background style of the header.
Tracks: openshiftio/openshift.io#3775
2. fix(styles): addresses minor alignment and style related bugs.
Tracks: openshiftio/openshift.io#3813
=>  fix(styles): addresses minor alignment and style related bugs.

src/app/add-dependency/add-dependency.component.html, src/app/add-dependency/add-dependency.component.less, src/app/add-dependency/add-dependency.component.ts, src/app/add-dependency/add-dependency.pipe.ts
Tracks: https://github.com/openshiftio/openshift.io/issues/3813
=> fix(ux): handles styles on click, handles count of all categories, modifies filter

src/app/add-dependency/add-dependency.component.html, src/app/add-dependency/add-dependency.component.less, src/app/add-dependency/add-dependency.component.ts, src/app/add-dependency/add-dependency.module.ts, src/app/add-dependency/add-dependency.spec.ts, src/app/add-dependency/maxlength.pipe.ts
Description: Currently, browse all dependencies modal inside dependency editor shows information such as
1. package name
2. category
3. security information
4. package version
This PR introduces description to enable the user understand more about the listed package.
=> feat(description): brings in description against each of the packages

src/app/add-dependency/add-dependency.component.ts
=> fix(improvement): avoids suggesting core dependencies in the browse all modal.

src/app/add-dependency/add-dependency.component.html, src/app/add-dependency/add-dependency.module.ts, src/app/add-dependency/add-dependency.spec.ts, src/app/alert-box/alert-box.component.html, src/app/alert-box/alert-box.module.ts, src/app/dependency-editor/dependency-editor.module.ts, src/app/dependency-editor/dependency-editor.spec.ts, src/app/insights/insights.component.html, src/app/insights/insights.module.ts, src/app/insights/insights.spec.ts, src/app/license/license.component.ts, src/app/security/security.component.ts
=> feat(tooltip): brings in tooltip to highlight the important information on hover.

src/app/add-dependency/add-dependency.component.html, src/app/add-dependency/add-dependency.component.less, src/app/add-dependency/add-dependency.component.ts, src/app/add-dependency/add-dependency.spec.ts, src/app/alert-box/alert-box.component.html, src/app/current-project/current-project.component.html, src/app/current-project/current-project.component.spec.ts, src/app/dependency-editor/dependency-editor.component.html, src/app/dependency-editor/dependency-editor.component.ts, src/app/dependency-editor/dependency-editor.module.ts, src/app/dependency-editor/dependency-editor.spec.ts, src/app/insights/insights.component.html, src/app/insights/insights.component.ts, src/app/license/license.component.html, src/app/license/license.component.ts, src/app/license/license.spec.ts, src/app/list-element/list-element.spec.ts, src/app/model/data.model.ts, src/app/security/security.component.html, src/app/security/security.component.ts, src/app/security/security.spec.ts, src/app/shared/dependency-editor.service.ts, src/app/shared/http-interceptor.ts
Description
1. This PR introduces a HTTP interceptor to handle errors at a single place.
2. Some minor ui changes
3. Addresses loaders properly
=> feat(error-handling): introduces error handling feature.

src/app/dependency-editor/dependency-editor.component.ts, src/app/insights/insights.component.html, src/app/insights/insights.component.ts, src/app/insights/insights.module.ts, src/app/insights/insights.spec.ts, src/app/shared/dependency-editor.service.ts
Tracks: https://github.com/openshiftio/openshift.io/issues/3874
https://github.com/openshiftio/openshift.io/issues/3863
=> feat(cache): handles removed dependencies in cache for current session.

src/app/add-dependency/add-dependency.component.ts
Description:
Currently the modal makes calls to the REST endpoint every time it is being opened.
As a result, this takes roughly **5 seconds** to process the response.
This PR handles that by doing the call on the background just once and cache the response for a specified input set as it won't ever change for that particular input set. This enables the modal to load instantaneously like a static modal **(0 seconds wait time)**.
This improves the users' experience as well.
Whenever the input set changes, a call is made to fetch the changed response which is then cached.
Tracks:
https://github.com/openshiftio/openshift.io/issues/3863
https://github.com/openshiftio/openshift.io/issues/3885
=> feat(performance): improves the load time performance of the modal drastically

src/app/add-dependency/add-dependency.component.ts, src/app/dependency-editor/dependency-editor.component.ts, src/app/insights/insights.component.less, src/app/insights/insights.component.ts
=> fix(bug): handle loading in insights sections to avoid collision with existing text

src/app/insights/insights.component.less, src/app/security/security.component.ts
=> fix(issue): fixes the security card

src/app/add-dependency/add-dependency.component.html, src/app/app.component.html, src/app/app.component.ts, src/app/dependency-editor/dependency-editor.component.html, src/app/dependency-editor/dependency-editor.component.ts, src/app/license/license.component.ts
Tracks : 
- https://github.com/openshiftio/openshift.io/issues/3244
=> Blank mission support for dependency editor

index.ts, package-lock.json, package.json, src/app/add-dependency/add-dependency.component.html, src/app/add-dependency/add-dependency.component.ts, src/app/insights/insights.component.ts, src/app/list-element/list-element.component.ts, src/app/shared/properties.spec.ts, src/app/shared/properties.ts, src/app/shared/telemetry.decorator.ts
- moved shared files from ngx-launcher to this repo
- added the broadcasting events to track the user behaviour
- User story :- https://github.com/openshiftio/openshift.io/issues/3239
=> fix(telemetry): added telemetry to dep editor

package-lock.json, package.json, src/app/add-dependency/add-dependency.component.html, src/app/add-dependency/add-dependency.component.ts, src/app/add-dependency/add-dependency.spec.ts, src/app/dependency-editor/dependency-editor.component.ts, src/app/dependency-editor/dependency-editor.module.ts, src/app/dependency-editor/dependency-editor.spec.ts, src/app/insights/insights.component.ts, src/app/insights/insights.spec.ts, src/app/list-element/list-element.component.ts, src/app/list-element/list-element.spec.ts, src/app/shared/dependency-editor.service.ts, src/app/shared/telemetry.service.ts, src/app/shared/woopra-key-map.ts
- This PR has the telemetry events added to track the user behaviour in dependency editor.
- Once this PR gets merged and a new version is released the new version has to be updated in ngx-launcher. And eventually the new version of ngx-launcher has to be updated in fabric8-ui
=> fix(telemetry): Added telemetry events for the dep editor

package.json
- added `semantic-release post` command to the semantic script
=> fix(semantic-release): updated semantic release script

README.adoc
- updates readme with env to be exported for running standalone
=> fix(readme): updates readme with env to be exported

cico_release.sh, cico_setup.sh, package-lock.json, package.json
- changes cico files
- updates semantic-release
=> fix(release): changes cico files and updates semantic-release
